import Navbar from "@/components/Navbar";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Separator } from "@/components/ui/separator";
import { Switch } from "@/components/ui/switch";
import { Settings as SettingsIcon, User, Shield, FileText } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

const Settings = () => {
  const { toast } = useToast();

  const handleSave = () => {
    toast({
      title: "Settings saved",
      description: "Your preferences have been updated successfully.",
    });
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-background to-muted/20">
      <Navbar />

      <div className="container mx-auto px-4 py-12 max-w-4xl">
        <div className="mb-8 animate-fade-in">
          <h1 className="text-4xl font-bold mb-2">Settings</h1>
          <p className="text-muted-foreground text-lg">
            Manage your account and preferences
          </p>
        </div>

        {/* Profile Settings */}
        <Card className="p-8 mb-6 animate-fade-in">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
              <User className="w-5 h-5 text-primary" />
            </div>
            <h2 className="text-2xl font-bold">Profile</h2>
          </div>

          <div className="space-y-4">
            <div className="grid md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="firstName">First Name</Label>
                <Input id="firstName" placeholder="John" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="lastName">Last Name</Label>
                <Input id="lastName" placeholder="Doe" />
              </div>
            </div>
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input id="email" type="email" placeholder="professor@university.edu" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="institution">Institution</Label>
              <Input id="institution" placeholder="University Name" />
            </div>
          </div>
        </Card>

        {/* Export Settings */}
        <Card className="p-8 mb-6 animate-fade-in">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 rounded-lg bg-accent/10 flex items-center justify-center">
              <FileText className="w-5 h-5 text-accent" />
            </div>
            <h2 className="text-2xl font-bold">Export Settings</h2>
          </div>

          <div className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="pdfHeader">PDF Header Text</Label>
              <Input
                id="pdfHeader"
                placeholder="AI Quiz Builder — Generated Quiz"
                defaultValue="AI Quiz Builder — Generated Quiz"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="pdfFooter">PDF Footer Template</Label>
              <Input
                id="pdfFooter"
                placeholder="Generated on {date} • Topic: {topic}"
                defaultValue="Generated on {date} • Topic: {topic} • Generated by {user_email}"
              />
              <p className="text-sm text-muted-foreground">
                Use {"{date}"}, {"{topic}"}, and {"{user_email}"} as placeholders
              </p>
            </div>
          </div>
        </Card>

        {/* Privacy & Data */}
        <Card className="p-8 mb-6 animate-fade-in">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 rounded-lg bg-secondary/10 flex items-center justify-center">
              <Shield className="w-5 h-5 text-secondary" />
            </div>
            <h2 className="text-2xl font-bold">Privacy & Data Retention</h2>
          </div>

          <div className="space-y-6">
            <div className="flex items-center justify-between">
              <div className="space-y-1">
                <Label htmlFor="storeData" className="text-base font-semibold">
                  Store generated content
                </Label>
                <p className="text-sm text-muted-foreground">
                  Save quiz sessions and questions to your account
                </p>
              </div>
              <Switch id="storeData" defaultChecked />
            </div>

            <Separator />

            <div className="space-y-2">
              <Label className="text-base font-semibold">Data Retention Period</Label>
              <div className="space-y-2">
                <label className="flex items-center gap-2 cursor-pointer">
                  <input type="radio" name="retention" value="30" className="w-4 h-4" />
                  <span className="text-sm">30 days</span>
                </label>
                <label className="flex items-center gap-2 cursor-pointer">
                  <input type="radio" name="retention" value="365" className="w-4 h-4" defaultChecked />
                  <span className="text-sm">1 year</span>
                </label>
                <label className="flex items-center gap-2 cursor-pointer">
                  <input type="radio" name="retention" value="never" className="w-4 h-4" />
                  <span className="text-sm">Never delete</span>
                </label>
              </div>
            </div>

            <Separator />

            <div className="p-4 bg-muted rounded-lg">
              <p className="text-sm text-muted-foreground">
                <strong>Privacy Notice:</strong> We store your generated questions securely and
                never share them with third parties. API keys are encrypted and never exposed
                in the frontend. You can delete your data at any time from your account settings.
              </p>
            </div>
          </div>
        </Card>

        {/* Save Button */}
        <div className="flex justify-end">
          <Button onClick={handleSave} size="lg" className="bg-gradient-hero hover:opacity-90">
            <SettingsIcon className="w-4 h-4 mr-2" />
            Save Settings
          </Button>
        </div>
      </div>
    </div>
  );
};

export default Settings;